// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[OpenParen-1]
	_ = x[CloseParen-2]
	_ = x[Symbol-3]
}

const _TokenKind_name = "EOFOpenParenCloseParenSymbol"

var _TokenKind_index = [...]uint8{0, 3, 12, 22, 28}

func (i TokenKind) String() string {
	if i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
